#      --- LOGGING CONFIGURATION ---
logging:
  level:
    root: INFO

#      --- ACTUATOR CONFIGURATION ---
management.endpoint:
  env:
    enabled: true
  health:
    enabled: true
    probes:
      enabled: true
    show-components: always
    show-details: always
  info:
    enabled: true

management.endpoints:
  enabled-by-default: false
  web:
    base-path: /manage
    exposure:
      include: "*"

management.health:
  readinessstate:
    enabled: true
  livenessstate:
    enabled: true

management.info:
  java:
    enabled: true

management.server:
  base-path: /
  port: 11011

#      --- SERVER CONFIGURATION ---
server:
  port: 11010
  servlet:
    application-display-name: ${spring.application.name}
    register-default-servlet: true
  shutdown: graceful

#      --- SPRING CORE CONFIGURATION ---
spring:
  application:
    name: price-list
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: "/static/**"

#      --- SPRING DATA JPA CONFIGURATION ---
spring.datasource:
  url: jdbc:h2:mem:prices
  username: prices
  password: cHJpY2Vz

spring.h2.console:
  enabled: true
  path: /db-console

spring.jpa.properties:
  hibernate.dialect: org.hibernate.dialect.H2Dialect

#      --- SPRINGDOC UI CONFIGURATION ---
springdoc:
  api-docs:
    enabled: true
  enable-hateoas: false
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    path: /api-docs.html
    operations-sorter: alpha
    url: /static/openapi/price-list.yml
  writer-with-default-pretty-printer: true